### ISSUE TITLE
Sorry, you do not have permission for that!

### ISSUE THREAD

**Issue by TemKaSD** [Grief-Code/IPS-Stats#1]
![2017-02-25_004836](https://cloud.githubusercontent.com/assets/6318282/23307617/e013aa08-faf3-11e6-8ff5-4c6dbd1b9805.png)

**Comment by Grief-Code** [comment]
Did you purchase a forum license for IPS? 
If yes message me here please shortly, so i can be sure: https://invisionpower.com/profile/546002-griefcode/

I told you I wont offer support on cracked versions.

**Comment by TemKaSD** [comment]
@Grief-Code I want to test the UPS, have not used. If I like, I'm sure to get a license. Now I just want to test.

**Comment by TemKaSD** [comment]
@Grief-Code https://invisionpower.com/demo

**Comment by Grief-Code** [comment]
Okay.
You need to remove the folder 'sharedstats' from your 'applications' folder. Then try again.

**Comment by TemKaSD** [comment]
@Grief-Code ?

**Comment by TemKaSD** [comment]
@Grief-Code thx
