### ISSUE TITLE
An error occurred (500 Error)

### ISSUE THREAD

**Issue by TemKaSD** [Grief-Code/IPS-Stats#2]
after install.
![2017-02-25_014706](https://cloud.githubusercontent.com/assets/6318282/23309849/016b199a-fafc-11e6-9931-01ce332d9939.png)

**Comment by Grief-Code** [comment]
Hm... it is due to the missing database info.

Go to your admin panel and insert database connection info.

**Comment by TemKaSD** [comment]
@Grief-Code I use to test localhost

**Comment by Grief-Code** [comment]
Please try 127.0.0.1

**Comment by TemKaSD** [comment]
@Grief-Code not work ((

**Comment by TemKaSD** [comment]
@Grief-Code 
![2017-02-25_175449](https://cloud.githubusercontent.com/assets/6318282/23329417/a607f1e4-fb83-11e6-83f1-fc11eb52339e.png)
![2017-02-25_175540](https://cloud.githubusercontent.com/assets/6318282/23329418/a6336ee6-fb83-11e6-9945-3e8b269e3a92.png)
![2017-02-25_175551](https://cloud.githubusercontent.com/assets/6318282/23329419/a6528bdc-fb83-11e6-8e9f-6e9180926db3.png)

**Comment by Grief-Code** [comment]
Please upload the output of `/uploads/logs/error.log`

**Comment by TemKaSD** [comment]
@Grief-Code clear

**Comment by Grief-Code** [comment]
Send me a link to your page shortly please. Also check the apache2 error log.

**Comment by TemKaSD** [comment]
error in database strukture.
