### ISSUE TITLE
member_id - 0

### ISSUE THREAD

**Issue by TemKaSD** [Grief-Code/IPS-Stats#5]
![2017-04-15_001627](https://cloud.githubusercontent.com/assets/6318282/25045542/3cdd2e42-2170-11e7-9a21-1b8815115521.png)

**Comment by TemKaSD** [comment]
![2017-04-15_080842](https://cloud.githubusercontent.com/assets/6318282/25057328/371d5cf6-21b2-11e7-82cd-550ed57b6d0f.png)

**Comment by hagiali** [comment]
probably you have the error because the server is rubattle.net

**Comment by TemKaSD** [comment]
The problem solved itself
